pr1
dascalubogdan/WebApplication1 pull request #1
Opened 2017-02-19 08:21 UTC by dascalubogdan

2017-02-25 08:05 UTC, dascalubogdan commented on WebApplication1.Tests/UnitTest1.cs
> +            //ssssdddsssdddssddddddddd
change

2017-02-25 08:05 UTC, dascalubogdan commented on WebApplication1.Tests/UnitTest1.cs
> +        [TestMethod]
change

2017-02-25 08:06 UTC, dascalubogdan commented on WebApplication1.Tests/UnitTest1.cs
> +        [TestMethod]
ok

2017-03-12 07:44 UTC, dascalubogdangmail requested changes
made some comments

2017-03-12 07:44 UTC, dascalubogdangmail commented on WebApplication1/WebApplication1.csproj
> -  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
undo this
@dascalubogdan

2017-03-12 07:46 UTC, dascalubogdangmail requested changes

2017-03-12 07:46 UTC, dascalubogdangmail commented on WebApplication1/Controllers/MeController.cs
> +        // GET api/Me sdasdasdasdaasdssssss
?

2017-03-12 07:49 UTC, dascalubogdangmail requested changes

2017-03-12 07:49 UTC, dascalubogdangmail commented on WebApplication1/WebApplication1.csproj
> -    <Error Condition="!Exists('..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.0\build\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props')" Text="$([System.String]::Format('
ggggg

2017-03-12 07:51 UTC, dascalubogdan commented
klose

2017-03-12 08:02 UTC, merged